version: '3'
networks:
  db-distribution-net:
services:
  otus-db-distribution-database:
    build:
      context: mongodb
      dockerfile: Dockerfile
    container_name: otus-db-distribution-database
    hostname: otus-db-distribution-database
    restart: always
    ports:
      - ${MONGO_PORT-27017}:27017
    volumes:
      - ./mongodb/persistence/mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=XRYs9yjU
    networks:
      - db-distribution-net
  otus-db-distribution-api:
    build:
      context: nodejs
      dockerfile: Dockerfile
    container_name: otus-db-distribution-api
    restart: always
    depends_on:
      - otus-db-distribution-database
    links:
      - otus-db-distribution-database
    env_file:
      - ./nodejs/.env
    ports:
      - ${API_PORT-7001}:${API_PORT-7001}
    environment: 
      - API_PORT=${API_PORT-7001}
      - MONGO_PORT=${MONGO_PORT-27017}
    networks:
      - db-distribution-net
